### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by wstoettinger** [saymedia/angularjs-server#28]
not sure if this was even intended to run on a windows machine, but it didn't state otherwise.

I installed node-gyp (a dependency) according to the description (https://www.npmjs.com/package/node-gyp) and when i require the module I get the following error:

i'm trying to get this to run with Meteor. 
The German error message is translated to. Error: %1 is not a valid Win32 application.

```
W20151128-17:29:14.459(1)? (STDERR) 
W20151128-17:29:14.460(1)? (STDERR) Error: %1 ist keine zulï¿½ssige Win32-Anwendung.
W20151128-17:29:14.460(1)? (STDERR) 
W20151128-17:29:14.461(1)? (STDERR) C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\build\Release\contextify.node
W20151128-17:29:14.461(1)? (STDERR)     at Module.load (module.js:356:32)
W20151128-17:29:14.461(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151128-17:29:14.461(1)? (STDERR)     at Module.require (module.js:364:17)
W20151128-17:29:14.461(1)? (STDERR)     at require (module.js:380:17)
W20151128-17:29:14.461(1)? (STDERR)     at bindings (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\bindings\bindings.js:76:44)
W20151128-17:29:14.461(1)? (STDERR)     at Object.<anonymous> (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\lib\contextify.js:1:34)
W20151128-17:29:14.462(1)? (STDERR)     at Module._compile (module.js:456:26)
W20151128-17:29:14.462(1)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151128-17:29:14.462(1)? (STDERR)     at Module.load (module.js:356:32)
W20151128-17:29:14.462(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151128-17:29:14.462(1)? (STDERR)     at Module.require (module.js:364:17)
W20151128-17:29:14.463(1)? (STDERR)     at require (module.js:380:17)
W20151128-17:29:14.463(1)? (STDERR) 	Error loading file:///C:/Users/wstoe/WebDev/Meteor/socially/.meteor/local/build/programs/server/server/main
W20151128-17:29:23.111(1)? (STDERR) 
W20151128-17:29:23.111(1)? (STDERR) Error: %1 ist keine zulï¿½ssige Win32-Anwendung.
W20151128-17:29:23.111(1)? (STDERR) 
W20151128-17:29:23.112(1)? (STDERR) C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\build\Release\contextify.node
W20151128-17:29:23.112(1)? (STDERR)     at Module.load (module.js:356:32)
W20151128-17:29:23.112(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151128-17:29:23.112(1)? (STDERR)     at Module.require (module.js:364:17)
W20151128-17:29:23.113(1)? (STDERR)     at require (module.js:380:17)
W20151128-17:29:23.113(1)? (STDERR)     at bindings (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\bindings\bindings.js:76:44)
=> Exited with code: 8
W20151128-17:29:23.113(1)? (STDERR)     at Object.<anonymous> (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\lib\contextify.js:1:34)
W20151128-17:29:23.114(1)? (STDERR)     at Module._compile (module.js:456:26)
W20151128-17:29:23.114(1)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151128-17:29:23.114(1)? (STDERR)     at Module.load (module.js:356:32)
W20151128-17:29:23.114(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151128-17:29:23.114(1)? (STDERR)     at Module.require (module.js:364:17)
W20151128-17:29:23.114(1)? (STDERR)     at require (module.js:380:17)
W20151128-17:29:23.115(1)? (STDERR) 	Error loading file:///C:/Users/wstoe/WebDev/Meteor/socially/.meteor/local/build/programs/server/server/main
W20151128-17:29:31.568(1)? (STDERR) 
W20151128-17:29:31.569(1)? (STDERR) Error: %1 ist keine zulï¿½ssige Win32-Anwendung.
W20151128-17:29:31.569(1)? (STDERR) 
W20151128-17:29:31.569(1)? (STDERR) C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\build\Release\contextify.node
W20151128-17:29:31.569(1)? (STDERR)     at Module.load (module.js:356:32)
W20151128-17:29:31.569(1)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151128-17:29:31.569(1)? (STDERR)     at Module.require (module.js:364:17)
W20151128-17:29:31.569(1)? (STDERR)     at require (module.js:380:17)
W20151128-17:29:31.570(1)? (STDERR)     at bindings (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\bindings\bindings.js:76:44)
W20151128-17:29:31.570(1)? (STDERR)     at Object.<anonymous> (C:\Users\wstoe\WebDev\Meteor\socially\node_modules\contextify\lib\contextify.js:1:34)
W20151128-17:29:31.570(1)? (STDERR)     at Module._compile (module.js:456:26)
W20151128-17:29:31.570(1)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151128-17:29:31.570(1)? (STDERR)     at Module.load (module.js:356:32)
```

**Comment by apparentlymart** [comment]
Honestly we have never attempted to run this code on Windows, so I can't speak to whether it would work there or not.

However, I do know that this module indirectly depends on another module called `contextify`, that has [a specific guide for installation on Windows](https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide), suggesting that it requires some unusual effort to get it working. I see `contextify` mentioned in your stack trace, so I'd start by trying to get `contextify` working in isolation first and then, once that's operating correctly, try to run AngularJS-Server with it.
