### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by asb14690** [saymedia/angularjs-server#40]
TypeError: Cannot read property 'ownerDocument' of null
    at Function.ga.contains (D:\angu_server\examples\Work\js\production.js:2:12161)
    at Function.n.extend.buildFragment (D:\angu_server\examples\Work\js\production.js:3:14234)
    at n.fn.extend.domManip (D:\angu_server\examples\Work\js\production.js:3:16823)
    at n.fn.extend.append (D:\angu_server\examples\Work\js\production.js:3:14908)
    at null._onTimeout (D:\angu_server\lib\main.js:203:51)
    at Timer.listOnTimeout (timers.js:92:15)

This happen when we add jquery library in module

**Comment by thrashr888** [comment]
I just had to fix an issue where the jsdom issue has changed. If you have a jsdom document object, try something like this: `document.documentElement`. jsdom now uses getters instead of throwing everything on the document object. Your bug actually helped me track this down, so thanks. :)
